In [1]:
!nvidia-smi

Sun Jan 29 22:43:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN Xp     On   | 00000000:85:00.0 Off |                  N/A |
| 23%   14C    P8     8W / 250W |      0MiB / 12196MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
""" 计算设备 """
import torch
from torch import nn

torch.cuda.device_count()

1

In [3]:
""" 尝试使用GPU """
def try_gpu(i=0):
    if torch.cuda.device_count() >= i+1:
        return torch.device(f"cuda:{i}")
    else:
        return torch.device("cpu")
    
def try_all_gpu():
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else torch.device("cpu")

try_gpu(), try_gpu(1), try_all_gpu()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

张量在GPU上计算

In [4]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [11]:
""" to GPU """
X = torch.arange(6, device=try_gpu(), dtype=torch.float32).reshape(2, 3)
X

tensor([[0., 1., 2.],
        [3., 4., 5.]], device='cuda:0')

In [12]:
Y = torch.rand(2, 3, device=try_gpu())
Y

tensor([[0.8627, 0.4736, 0.8902],
        [0.3698, 0.7629, 0.8081]], device='cuda:0')

In [13]:
""" 计算操作需要在相同设备 """
X + Y

tensor([[0.8627, 1.4736, 2.8902],
        [3.3698, 4.7629, 5.8081]], device='cuda:0')

In [14]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())
net(X)

tensor([[0.8110],
        [0.3029]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [16]:
net[0].weight.data.device

device(type='cuda', index=0)

In [17]:
torch.cuda.is_available()

True

In [18]:
X = torch.arange(12)

In [19]:
X.to(device=try_gpu())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], device='cuda:0')